### ISSUE TITLE
Move Enzyme/React to peer dependencies?

### ISSUE THREAD

**Issue by jdcrensh** [joetidee/enzyme-react-intl#1]
Enzyme, react, react-dom are most likely already installed by the project that installs `enzyme-react-intl`. They should be listed as peer dependencies instead to avoid versioning issues and duplication.

**Comment by joetidee** [comment]
Do you mean instead of actually including them in the enzyme-react-intl package itself?

**Comment by jdcrensh** [comment]
Yes, example:

```json
"dependencies": {
    "jsonfile": "^2.4.0"
},
"peerDependencies": {
    "enzyme": "^2.7.1",
    "react": "^15.4.1",
    "react-dom": "^15.4.2",
    "react-intl": "^2.2.3"
}
```

npm/yarn warns if any peer dependencies listed aren't installed.

**Comment by joetidee** [comment]
Thanks for the advice.
