### ISSUE TITLE
ShallowWithIntl: Supprt enzyme3 options?

### ISSUE THREAD

**Issue by nelsonchen90** [joetidee/enzyme-react-intl#13]
We can pass optional arguements `options` to shallow renderer in Enzyme 3:
http://airbnb.io/enzyme/docs/api/shallow.html#arguments

but the implementation here doesn't support it
https://github.com/joetidee/enzyme-react-intl/blob/3088da7126a1d9166366c0af5914eefca68122ec/src/index.js#L44

any plans?

**Comment by joetidee** [comment]
Feel free to open a PR.
