### ISSUE TITLE
State on a component initiated with mountWithIntl returns null

### ISSUE THREAD

**Issue by rawroland** [joetidee/enzyme-react-intl#2]
Calling the state method on a component which was mounted with `mountWithIntl` returns null, even though the component should have state. Have not been able to identify what the problem is.

**Comment by joetidee** [comment]
Can you provide a code snippet?

**Comment by raywongjr** [comment]
Running into similar issue with following code.

```
const wrapper = shallowWithIntl(<MyComponent />);
wrapper.state().foo// returns error
```
