### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by dev-cprice** [joetidee/enzyme-react-intl#22]
Can you deploy a new release to npm?

Would love to be able to use the result of https://github.com/joetidee/enzyme-react-intl/pull/18

**Comment by joetidee** [comment]
Npm already has 2.0.3 published - is this not correct?

**Comment by dev-cprice** [comment]
The `2.0.3` tag here on Github may point to the latest master,
![image](https://user-images.githubusercontent.com/34115417/50918694-90033780-1406-11e9-9e07-44bb7fb5363c.png)
but according to [the npm page](https://www.npmjs.com/package/enzyme-react-intl), the artifact hasn't been released in 3 months:
![image](https://user-images.githubusercontent.com/34115417/50918602-4f0b2300-1406-11e9-8a4b-b91da7508ffc.png)

**Comment by dev-cprice** [comment]
This is from using the "latest" `2.0.3` from `npm`, unminified:

![image](https://user-images.githubusercontent.com/34115417/50919667-0a34bb80-1409-11e9-9228-ece9f46ca813.png)

which is what it looked like before #18: https://github.com/joetidee/enzyme-react-intl/blob/212bc9b459e738defe566411afb06d62a0947969/src/index.js#L6
 
after #18: https://github.com/joetidee/enzyme-react-intl/blob/542107351bcc51f41e10eabb69710b6c33b8a306/src/index.js#L6-L7

**Comment by joetidee** [comment]
Just re-published to npm.
