### ISSUE TITLE
loadTranslation doesn't properly resolve path

### ISSUE THREAD

**Issue by timtime4** [joetidee/enzyme-react-intl#3]
I'm trying to use loadTranslation as such `loadTranslation('../locales/en.json');` but I'm getting an error that reads: `ENOENT: no such file or directory, open './locales/en.json'`.

I am confident that I'm providing the correct path to that file as well.

**Comment by joetidee** [comment]
Could you let me know if you solved this, or, provide an example of the path you are using?

**Comment by zanza00** [comment]
I had the same problem, my solution is to start the path from the root of the project

`loadTranslation('./app/translations/en.json');`

hope this helps :)

**Comment by joetidee** [comment]
@timtime4 I have updated the Readme file to help others. Can you confirm that this has fixed it for you?

**Comment by timtime4** [comment]
I'm sorry - I'm no longer working on the project where I had this issue and do not have access to the code anymore

**Comment by batjko** [comment]
I have run into this as well and am now failing most of my tests (which worked fine before using this package).
Somehow all my assertions are suddenly wrong, e.g.:
```js
 it('contains 2 buttons', () => {
    const wrapper = shallowWithIntl(<MyComp />)
    expect(wrapper.find('Button').length).toEqual(2) // this was fine before, now claims to be 0 !
  })
```
