### ISSUE TITLE
How can I add locale data to my tests

### ISSUE THREAD

**Issue by anopheles** [joetidee/enzyme-react-intl#4]
In my main app I do something like this

```
import {addLocaleData, IntlProvider} from 'react-intl';
import de from 'react-intl/locale-data/de';
addLocaleData(de);
```

If I do this in my test and render a component formatted date 

```
export const datecomponent = injectIntl(({date}) => {
    if (!date) {
        return (<div>-</div>);
    }
    let parsedDate = new Date(parseInt(date));
    return (<div>
        <div><FormattedTime value={parsedDate}/> <FormattedDate value={parsedDate}/></div>
    </div>);
});

```

I always get the default english locale, i.e. something like this: 1:10 PM 8/10/2017
But I want something like this 13:10 10.8.2017

**Comment by anopheles** [comment]
This might be related to 
https://github.com/yahoo/react-intl/issues/274

**Comment by acanimal** [comment]
You have the `loadTranslation` and `setLocale` methods: https://github.com/joetidee/enzyme-react-intl/blob/master/src/index.js#L17
